# Stage 1: Build the application (builder stage)
FROM node:20-alpine AS builder
WORKDIR /backend
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run dist

# Stage 2: Create the final image (production stage)
FROM node:20-alpine
WORKDIR /app
COPY --from=builder /backend/dist ./dist
COPY --from=builder /backend/node_modules ./node_modules
COPY package*.json ./
ENV NODE_ENV production
COPY .env.production .
EXPOSE 5000
CMD ["npm", "start"]
